# Generated by Django 6.1 on 2026-08-30 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cisterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField()),
                ('cisterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='monitoramento.cisterna')),
            ],
        ),
        migrations.CreateModel(
            name='LeituraTelemetria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.FloatField()),
                ('data_hora', models.DateTimeField()),
                ('cisterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='monitoramento.cisterna')),
            ],
        ),
        migrations.AddField(
            model_name='cisterna',
            name='localidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cisternas', to='monitoramento.localidade'),
        ),
        migrations.AddField(
            model_name='cisterna',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cisternas', to='monitoramento.participante'),
        ),
    ]
