# Generated by Django 6.1 on 2026-09-26 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='cisterna',
            name='capacidade_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cisterna',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cisternas/'),
        ),
        migrations.AddField(
            model_name='cisterna',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cisterna',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cisterna',
            name='situacao',
            field=models.CharField(choices=[('normal', 'Normal'), ('atencao', 'Atenção'), ('critico', 'Crítico'), ('sem_dados', 'Sem dados')], default='sem_dados', max_length=20),
        ),
        migrations.AddField(
            model_name='cisterna',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cisternas', to='monitoramento.municipio'),
        ),
    ]
