# Generated by Django 6.1 on 2026-09-27 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_municipio_cisterna_capacidade_total_cisterna_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=100, unique=True)),
                ('tipo_sensor', models.CharField(max_length=100)),
                ('data_instalacao', models.DateField()),
                ('situacao', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('manutencao', 'Em manutenção')], default='ativo', max_length=20)),
                ('cisterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='monitoramento.cisterna')),
            ],
        ),
        migrations.AddField(
            model_name='leituratelemetria',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leituras', to='monitoramento.dispositivo'),
        ),
    ]
