# Generated by Django 6.1 on 2026-10-02 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0003_dispositivo_leituratelemetria_dispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidade',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='localidade',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='localidade',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='localidades', to='monitoramento.municipio'),
        ),
    ]
