# Generated by Django 6.1 on 2026-10-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0004_localidade_descricao_localidade_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidade',
            name='municipio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
